export const GET_TECHNICIANS = 'GET_TECHNICIANS';
export const ADD_TECHNICIAN = 'ADD_TECHNICIAN';
export const UPDATE_TECHNICIAN = 'UPDATE_TECHNICIAN';
export const DELETE_TECHNICIAN = 'DELETE_TECHNICIAN';
